# Generated by Django 4.2.19 on 2025-02-11 17:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
